# For typical data storage management
mysql56:
  image: mysql:5.6
  ports:
    - "3333:3306"
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=abc123
    - MYSQL_USER=rockfishdev
    - MYSQL_PASSWORD=I4mrockf!sh